### ISSUE TITLE
Craft 3.6 compatibility

### ISSUE THREAD

**Issue by zawilliams** [venveo/craft-redactor-split#2]
I can't get this to show up in Craft 3.6 - is this plugin compatible?

**Comment by Mosnar** [comment]
I'll take a look! Thanks for reporting.

**Comment by extensibleseth** [comment]
I had to uninstall, and re-install the plugin for redactor to find 'redactor-split' after upgrading to Craft 3.6. I'm getting a JavaScript error when clicking it now.

```

Uncaught TypeError: can't access property "nextElementSibling", currentNode is null
    _splitMatrix redactor-split.js:83
    split redactor-split.js:108
    callInstanceMethod redactor.js:2383
    api redactor.js:2354
    toggle redactor.js:5124
    on redactor.js:889
    each redactor.js:248
    on redactor.js:880
    _buildCallback redactor.js:5177
    _init redactor.js:5144
    init redactor.js:5015
    create redactor.js:1503
    addButton RedactorOverrides.js:423
    start redactor-split.js:65
    callInstanceMethod redactor.js:2383
    _startStop redactor.js:10556
    onenable redactor.js:10538
    callMessageHandler redactor.js:2263
    broadcast redactor.js:2285
    start redactor.js:2132
    App redactor.js:2115
    RedactorApp redactor.js:1401
    redactor redactor.js:1380
    initRedactor RedactorInput.js:159
    init RedactorInput.js:143
    constructor garnish.js:764
    constructor garnish.js:40
    constructor garnish.js:40
    <anonymous> 15:2222
    jQuery 13
redactor-split.js:83:17
    _splitMatrix redactor-split.js:83
    split redactor-split.js:108
    callInstanceMethod redactor.js:2383
    api redactor.js:2354
    toggle redactor.js:5124
    toggle self-hosted:1173
    (Async: EventListener.handleEvent)
    on redactor.js:889
    each redactor.js:248
    on redactor.js:880
    _buildCallback redactor.js:5177
    _init redactor.js:5144
    init redactor.js:5015
    create redactor.js:1503
    addButton RedactorOverrides.js:423
    start redactor-split.js:65
    callInstanceMethod redactor.js:2383
    _startStop redactor.js:10556
    onenable redactor.js:10538
    callMessageHandler redactor.js:2263
    broadcast redactor.js:2285
    start redactor.js:2132
    App redactor.js:2115
    RedactorApp redactor.js:1401
    redactor redactor.js:1380
    initRedactor RedactorInput.js:159
    init RedactorInput.js:143
    constructor garnish.js:764
    constructor garnish.js:40
    constructor garnish.js:40
    <anonymous> 15:2222
```

**Comment by Mosnar** [comment]
I'm having trouble reproducing these issues right now, everything appears to be working on my end. Currently testing on the Craft 3.7-dev branch.

**Comment by Mosnar** [comment]
Just released 1.1.1 that should fix this

**Comment by iparr** [comment]
I'm getting the same issue. Currently on 3.6.12.1

I've installed via the Plugin Store. Then uninstalled and tried via `composer require venveo/craft-redactor-split` but neither seems to work. The plugin is marked as enabled in the Plugins page, but when I try to edit an article I get `Redactor plugin not found: redactor-split`

**Comment by chadcrowell** [comment]
I tried removing the plugin on 3.7.36 (just trying to thin out plugin usage on a site) and am also getting `Redactor plugin not found: redactor-split` after the plugin is uninstalled and removed. Its like Redactor still expects it to be there even though the vendor folder is gone and the uninstall/removal went fine. Maybe it is still showing in the project config?

**Comment by Mosnar** [comment]
Going to close this out since I just released v4 with Craft 4 support and confirmed everything is working as expected. Feel free to bump this back open if it's still an issue though - especially if it's still a problem in a Craft 4. 

Thanks for everyone's patience!
